### ISSUE TITLE
Búsqueda de usuarios

### ISSUE THREAD

**Issue by rigel281** [Project-Rigel/rigel-admin-panel#6]
Si busco solo soler no salen nada y deberia salir todos aquellos que tengan soler en cualquier sitio.

**Comment by EduardoSimon** [comment]
![image](https://user-images.githubusercontent.com/19764148/81093080-df298180-8f01-11ea-9745-0d1bf871d10f.png)

Esta es la vista actual de la pestaña de pacientes. Cual deberia ser el funcionamiento ideal de esa barra de busqueda? Existen dos opciones:

1. O bien se hace una busqueda con cualquier match del texto. Ejemplo: Eduardo SImon Picon . Si busco co, saldra como posible resultado

2.Busqueda solo con las primeras letras del nombre y apellidos. Ejemplo: Eduardo Simon Picon solo sale si busco Ed o Si o Pi.

La primera solucion hace que sea necesario un sistema externo de indexacion de los datos. Mientras que la segunda lo podemos hacer con las herramientas que contamos.

**Comment by rigel281** [comment]
Cuando click en customers me sale pantalla y dice no hay clientes. Si busco en la barra ya aparecen. Deberían aparecer desde el principio.

**Comment by rigel281** [comment]
Búsqueda con primeras letras.

**Comment by EduardoSimon** [comment]
Que es la búsqueda con primeras letras?

**Comment by EduardoSimon** [comment]
- [ ] Añadir texto cuando no encuentra nada

**Comment by EduardoSimon** [comment]
- [ ] hola

**Comment by rigel281** [comment]
> - [] hola

Hola

**Comment by rigel281** [comment]
> > - [] hola
> 
> Hola

Hola

**Comment by rigel281** [comment]
Debe desaparecer anuncio en rojo del footer y aparecer anuncio apple en el centro solo para el correo incorrecto.

**Comment by rigel281** [comment]
Creo que lo cerré por error

**Comment by EduardoSimon** [comment]
[CLIENTE]quiere [poder buscar un usuario] para poder gestionar sus detalles

**Comment by EduardoSimon** [comment]
- [ ] Quitar footer rojo y añadir alert nativa de apple
